version: '2'
services:
    consul:
        image: consul:v0.7.0 
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        volumes:
            - ./consul-conf:/consul-conf
        command: consul agent -dev -ui -client 0.0.0.0 -config-dir /consul-conf

    consul-config-loader:
        image: jhipster/consul-config-loader:v0.1.2
        volumes:
            - ./central-server-config:/config
        environment:
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul
            - CONSUL_PORT=8500
            - MASTER_ACL_TOKEN=BE786B3B-CF10-401A-A867-B6F9E4CB1597
            - CLIENT_ACL_TOKEN=F09657B4-96B8-4A85-8409-09B9A7369A46

