version: '2'
services:
    gateway-app:
        image: gateway
        external_links:
            - gateway-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_CLOUD_CONSUL_TOKEN=BE786B3B-CF10-401A-A867-B6F9E4CB1597  
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - SPRING_CLOUD_CONFIG_URI=http://admin:undefined@registry:8761/config
        ports:
            - 8080:8080
    gateway-postgresql:
        container_name: gateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    
    todo-app:
        image: todo
        external_links:
            - todo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_CLOUD_CONSUL_TOKEN=BE786B3B-CF10-401A-A867-B6F9E4CB1597  
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/todo
            - JHIPSTER_SLEEP=10
            - SPRING_CLOUD_CONFIG_URI=http://admin:undefined@registry:8761/config
    todo-postgresql:
        container_name: todo-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=todo
            - POSTGRES_PASSWORD=
    
    consul:
        extends:
            file: consul.yml
            service: consul
    consul-config-loader:
        extends:
            file: consul.yml
            service: consul-config-loader

